embeddings:
  embedding_model_name: "google/embeddinggemma-300m"
  chunk_size: 512
  vectorstore_path: "data/vectorstores/ceo_docs_faiss"

llm:
  llm_framework: "gemini" # "huggingface"
  model_choices: ["gemini-2.5-flash","gemini-2.0-flash"]
  max_output_tokens: 8192
  prompt_file: "conf/base/prompts.yml"

