embedding_model_name: "google/embeddinggemma-300m"
chunk_size: 512
reader_model_name: "Qwen/Qwen3-4B-Instruct-2507"
vectorstore_path: "data/vectorstores/ceo_docs_faiss"
prompt_file: "conf/base/prompts.yml"
