embedding_model_name: "google/embeddinggemma-300m"
chunk_size: 512
llm_framework: "gemini" # "huggingface"
model_choices: ["gemini-2.5-flash","gemini-2.0-flash"] # ["Qwen/Qwen3-4B-Instruct-2507"]
vectorstore_path: "data/vectorstores/ceo_docs_faiss"
prompt_file: "conf/base/prompts.yml"